#!/usr/bin/env python3
from pathlib import Path
import json
import re

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
TARGETS = [ROOT / 'static-preview' / 'app.js', REPO / 'PTU_Companion_Android_Tauri' / 'www' / 'app.js']
SOURCE_CATALOG = json.loads((REPO / 'docs' / 'data' / 'PTU_COMBAT_SOURCE_PRECEDENCE.json').read_text(encoding='utf-8'))

HELPERS = (
    'const PTU_COMBAT_SOURCE_PRECEDENCE=' + json.dumps(SOURCE_CATALOG['sources'], ensure_ascii=False, separators=(',', ':')) + ';\n'
    + 'const PTU_COMBAT_SOURCE_OVERRIDES=' + json.dumps(SOURCE_CATALOG['overrides'], ensure_ascii=False, separators=(',', ':')) + ';\n'
    + r'''function pokemonCombatSourceKey(row){const d=row?.definition||row?.record||row||{};return String(row?.sourceId||row?.source_id||d.sourceId||d.source_id||row?.source||d.source||d.sourceTitle||d.source_title||'').toLowerCase();}
function pokemonCombatSourceRank(row){const key=pokemonCombatSourceKey(row);const found=PTU_COMBAT_SOURCE_PRECEDENCE.find(s=>key.includes(s.id)||key.includes(s.label.toLowerCase()));return found?.rank||100;}
function pokemonCombatSourceOverride(row){const name=pokemonCombatSlug(row?.name||row?.definition?.name||row?.record?.name),override=PTU_COMBAT_SOURCE_OVERRIDES[name],d=row?.definition||row?.record||{};return override?{...row,definition:{...d,...override}}:row;}
function pokemonCombatResolveDefinition(rows,name){const wanted=pokemonCombatSlug(name);const candidates=(rows||[]).filter(row=>pokemonCombatSlug(row?.name||row?.definition?.name||row?.record?.name)===wanted).map(pokemonCombatSourceOverride);return candidates.map((row,index)=>({row,rank:pokemonCombatSourceRank(row),index})).sort((a,b)=>b.rank-a.rank||b.index-a.index)[0]?.row||null;}
function pokemonCombatResolvedSource(row){const rank=pokemonCombatSourceRank(row);return PTU_COMBAT_SOURCE_PRECEDENCE.find(s=>s.rank===rank)||PTU_COMBAT_SOURCE_PRECEDENCE[0];}
function pokemonCombatElectrodashDefinition(rows){return pokemonCombatResolveDefinition(rows,'Electrodash');}
'''
)

QUICK_CURL = r'''function pokemonCombatQuickCurlAbilityResourceSpec(){return pokemonCombatNonMoveSpec('ability','combat-quick-curl','Quick Curl','Free Action','Scene');}
function pokemonCombatQuickCurlDefenseResourceSpec(variant='core'){return pokemonCombatNonMoveSpec('move','defense-curl-quick-curl','Defense Curl via Quick Curl',variant==='february-2016'?'Standard Action':'Swift Action','At-Will');}
function pokemonCombatQuickCurlAbilityRow(data){return pokemonCombatResolveDefinition(data?.abilities,'Quick Curl');}
function pokemonCombatQuickCurlDefenseMoveRow(data){return pokemonCombatResolveDefinition(data?.moves,'Defense Curl');}
function pokemonCombatQuickCurlVariant(row){const effect=String(row?.definition?.effect||'').toLowerCase().replace(/[^a-z0-9+]+/g,' ');if(effect.includes('standard action interrupt')&&effect.includes('10 damage reduction'))return 'february-2016';if(effect.includes('use defense curl as a swift action'))return 'core';return null;}
function pokemonCombatQuickCurlAbilitySourceMatches(row){return pokemonCombatQuickCurlVariant(row)!==null;}
function pokemonCombatQuickCurlDefenseSourceMatches(row){if(!row||pokemonCombatSlug(row?.definition?.name||row?.record?.name)!=='defense-curl')return false;const frequency=String(row.definition?.frequency||row.record?.frequency||'At-Will');return !frequency||/^at-will$/i.test(frequency.trim());}
function pokemonCombatQuickCurlAvailability(id,data){const abilityRow=pokemonCombatQuickCurlAbilityRow(data),moveRow=pokemonCombatQuickCurlDefenseMoveRow(data),variant=pokemonCombatQuickCurlVariant(abilityRow);if(!abilityRow||!variant)return {valid:false,reason:'The resolved Quick Curl definition is not an audited supplied-source variant.'};if(!moveRow||!pokemonCombatQuickCurlDefenseSourceMatches(moveRow))return {valid:false,abilityRow,reason:'Defense Curl is not available from the active Ruleset.'};const ledger=pokemonCombatParticipant(id,{create:false});if(!ledger)return {valid:false,reason:'Put this Pokémon in Combat first.'};if(ledger.moveState?.rollout?.active)return {valid:false,reason:'Rollout is active; the user must continue Rollout.'};const ability=pokemonCombatQuickCurlAbilityResourceSpec(),abilityCheck=pokemonCombatNonMoveAvailability(id,ability),defense=pokemonCombatQuickCurlDefenseResourceSpec(variant),defenseCheck=pokemonCombatNonMoveAvailability(id,defense);return abilityCheck.valid&&defenseCheck.valid?{valid:true,abilityRow,moveRow,variant,ability,defense}:{valid:false,abilityRow,moveRow,variant,ability,defense,reason:abilityCheck.reason||defenseCheck.reason};}
function pokemonCombatQuickCurlSpendResources(id,data,{log=true}={}){const check=pokemonCombatQuickCurlAvailability(id,data);if(!check.valid)return check;const sequence=Number(pokemonCombatParticipant(id,{create:false})?.resourceSequence||0),compositeId=`quick-curl-composite-${sequence}`,abilitySpend=pokemonCombatSpendNonMoveResource(id,check.ability,{log:false});if(!abilitySpend.valid)return abilitySpend;const defenseSpend=pokemonCombatSpendNonMoveResource(id,check.defense,{log:false});if(!defenseSpend.valid){pokemonCombatRefundNonMoveResourceCore(id,abilitySpend.transaction?.id,{log:false});return defenseSpend;}for(const [transaction,role] of [[abilitySpend.transaction,'ability'],[defenseSpend.transaction,'move']])if(transaction){transaction.compositeId=compositeId;transaction.compositeRole=role;}if(log)pokemonCombatLog(id,'Resources spent',`Quick Curl · Scene Free · Defense Curl · ${defenseSpend.action?.spent||check.defense.actionCost}.`,'resource');return {...check,abilitySpend,defenseSpend,compositeId,transactions:[abilitySpend.transaction,defenseSpend.transaction].filter(Boolean)};}
async function pokemonCombatUseQuickCurlDefenseCurl(id){const p=pokemon(id),data=pokemonCombatReferenceState.pokemonId===id?pokemonCombatReferenceState.data:null,spent=pokemonCombatQuickCurlSpendResources(id,data,{log:true});if(!spent.valid)return toast(spent.reason||'Quick Curl is unavailable.','error');const ledger=pokemonCombatParticipant(id),action=spent.defenseSpend.action?.spent||spent.defense.actionCost;ledger.conditions.curledUp=true;if(spent.variant==='february-2016')ledger.conditions.quickCurlDrRound=Number(state.ui.round||1);pokemonCombatLog(id,'Quick Curl',`${p.name} used resolved ${spent.variant==='february-2016'?'February 2016':'Core'} Quick Curl · ${action}.`,'ability');await pokemonCombatDispatchMoveFormEvent(id,spent.moveRow);await commit(`${p.name} used Quick Curl + Defense Curl.`);render();return {valid:true,spent};}
function pokemonCombatQuickCurlPanel(id,data){const available=pokemonCombatQuickCurlAvailability(id,data);if(!available.abilityRow)return '';const feb=available.variant==='february-2016',label=feb?'Defense Curl · Standard Interrupt + DR 10':'Defense Curl · Swift Action';return `<article class="ability-card"><h3>Quick Curl + Defense Curl</h3><p>${feb?'February 2016 override: use Defense Curl as a Standard Action Interrupt; +10 DR is tracked for this round.':'Core: use Defense Curl as a Swift Action.'}</p><button class="btn ${available.valid?'btn-gold':'btn-disabled'} full" ${available.valid?'':'disabled'} onclick="pokemonCombatUseQuickCurlDefenseCurl('${id}')">${label}</button></article>`;}'''

ELECTRODASH = r'''function pokemonCombatElectrodashResourceSpec(){return pokemonCombatNonMoveSpec('ability','combat-electrodash','Electrodash','Swift Action','Scene x2');}
function pokemonCombatElectrodashAvailability(id,data){const row=pokemonCombatElectrodashDefinition(data?.abilities);if(!row)return {valid:false,reason:'This Pokémon does not have Electrodash.'};const effect=String(row.definition?.effect||'').toLowerCase();if(!effect.includes('sprint action as a free action'))return {valid:false,row,reason:'The resolved Electrodash definition is not the audited February 2016 version.'};const resource=pokemonCombatElectrodashResourceSpec(),check=pokemonCombatNonMoveAvailability(id,resource);return check.valid?{valid:true,row,resource}:{...check,row,resource};}
async function pokemonCombatUseElectrodashSprint(id){const p=pokemon(id),data=pokemonCombatReferenceState.pokemonId===id?pokemonCombatReferenceState.data:null,check=pokemonCombatElectrodashAvailability(id,data);if(!check.valid)return toast(check.reason||'Electrodash is unavailable.','error');const spent=pokemonCombatSpendNonMoveResource(id,check.resource,{log:false});if(!spent.valid)return toast(spent.reason,'error');const ledger=pokemonCombatParticipant(id);ledger.conditions.electrodashSprintRound=Number(state.ui.round||1);pokemonCombatLog(id,'Electrodash',`${p.name} used Sprint as a Free Action · February 2016 Electrodash · ${spent.action?.spent||'Swift Action'} · Scene x2.`,'ability');await commit(`${p.name} used Electrodash + Sprint.`);render();return {valid:true,spent};}
function pokemonCombatElectrodashClearStuckAvailability(id,data){const row=pokemonCombatElectrodashDefinition(data?.abilities),ledger=pokemonCombatParticipant(id,{create:false});if(!row||!ledger?.conditions?.stuck)return {valid:false,row,reason:'This Pokémon is not Stuck.'};const bonus=String(row.definition?.bonus||'').toLowerCase();if(!bonus.includes('free itself from the stuck condition'))return {valid:false,row,reason:'The resolved Electrodash definition does not grant Stuck removal.'};return pokemonCombatCanSpendAction(id,'Shift Action');}
async function pokemonCombatUseElectrodashClearStuck(id){const data=pokemonCombatReferenceState.pokemonId===id?pokemonCombatReferenceState.data:null,check=pokemonCombatElectrodashClearStuckAvailability(id,data);if(!check.valid)return toast(check.reason||'Stuck removal is unavailable.','error');const spent=pokemonCombatSpendAction(id,'Shift Action'),ledger=pokemonCombatParticipant(id);ledger.conditions.stuck=false;pokemonCombatLog(id,'Electrodash',`${pokemon(id)?.name||id} cleared Stuck · ${spent.spent}.`,'ability');await commit(`${pokemon(id)?.name||'Pokémon'} cleared Stuck with Electrodash.`);render();return {valid:true,spent};}
function pokemonCombatSetStuck(id,stuck){const ledger=pokemonCombatParticipant(id);ledger.conditions.stuck=!!stuck;pokemonCombatLog(id,stuck?'Stuck':'Stuck cleared',`${pokemon(id)?.name||id} was marked ${stuck?'Stuck':'not Stuck'} manually.`,'condition');commit(`${pokemon(id)?.name||'Pokémon'} Stuck state updated.`);render();}
function pokemonCombatElectrodashPanel(id,data){const available=pokemonCombatElectrodashAvailability(id,data),clear=pokemonCombatElectrodashClearStuckAvailability(id,data);if(!available.row)return '';const button=(label,check,fn)=>`<button class="btn ${check.valid?'btn-gold':'btn-disabled'} full" ${check.valid?'':'disabled'} onclick="${fn}">${label}</button>`;return `<article class="ability-card"><h3>Electrodash + Sprint</h3><p>February 2016: Sprint is a Free Action; no Attacks of Opportunity while Sprinting.</p>${button('Use Electrodash + Sprint · Free + Swift · Scene x2',available,`pokemonCombatUseElectrodashSprint('${id}')`)}${button('Electrodash · clear Stuck · Shift Action',clear,`pokemonCombatUseElectrodashClearStuck('${id}')`)}</article>`;}'''

PRIME_FURY = r'''function pokemonCombatPrimeFuryResourceSpec(){return pokemonCombatNonMoveSpec('ability','combat-prime-fury','Prime Fury','Swift Action','Scene');}
function pokemonCombatPrimeFuryAvailability(id,data){const row=pokemonCombatResolveDefinition(data?.abilities,'Prime Fury');if(!row)return {valid:false,reason:'This Pokémon does not have Prime Fury.'};const effect=String(row.definition?.effect||'').toLowerCase();if(!effect.includes('becomes enraged')||!effect.includes('special attack'))return {valid:false,row,reason:'The resolved Prime Fury definition is not the audited February 2016 version.'};const resource=pokemonCombatPrimeFuryResourceSpec(),check=pokemonCombatNonMoveAvailability(id,resource);return check.valid?{valid:true,row,resource}:{...check,row,resource};}
async function pokemonCombatUsePrimeFury(id){const p=pokemon(id),data=pokemonCombatReferenceState.pokemonId===id?pokemonCombatReferenceState.data:null,check=pokemonCombatPrimeFuryAvailability(id,data);if(!check.valid)return toast(check.reason||'Prime Fury is unavailable.','error');const spent=pokemonCombatSpendNonMoveResource(id,check.resource,{log:false});if(!spent.valid)return toast(spent.reason,'error');pokemonCombatApplySelfStatuses(id,['Enraged'],'Prime Fury');pokemonCombatApplyCombatStages(id,{attack:1,spAttack:1},'Prime Fury');pokemonCombatLog(id,'Prime Fury',`${p.name} became Enraged · Attack +1 CS · Special Attack +1 CS.`,'ability');await commit(`${p.name} used Prime Fury.`);render();return {valid:true,spent};}
function pokemonCombatPrimeFuryPanel(id,data){const available=pokemonCombatPrimeFuryAvailability(id,data),enraged=!!pokemonCombatParticipant(id,{create:false})?.conditions?.enraged;if(!available.row)return '';return `<article class="ability-card"><h3>Prime Fury</h3><p>February 2016: become Enraged; Attack and Special Attack each rise by +1 Combat Stage.</p>${enraged?'<div class="flow-note"><small>Enraged is active.</small></div>':''}<button class="btn ${available.valid?'btn-gold':'btn-disabled'} full" ${available.valid?'':'disabled'} onclick="pokemonCombatUsePrimeFury('${id}')">Use Prime Fury · Swift Action · Scene</button></article>`;}'''

HYDRATION_ICE_BODY = r'''function pokemonCombatHydrationRow(data){return pokemonCombatResolveDefinition(data?.abilities,'Hydration');}
function pokemonCombatIceBodyRow(data){return pokemonCombatResolveDefinition(data?.abilities,'Ice Body');}
function pokemonCombatSetWeather(value){state.ui.weather=['rain','hail'].includes(value)?value:'clear';commit(`Combat weather set to ${state.ui.weather}.`);render();}
function pokemonCombatSetStatusAffliction(id,status,active){const ledger=pokemonCombatParticipant(id),items=new Set(ledger.conditions.statusAfflictions||[]);active?items.add(status):items.delete(status);ledger.conditions.statusAfflictions=[...items];pokemonCombatLog(id,active?'Status Affliction marked':'Status Affliction cleared',`${status} ${active?'marked active':'cleared'} manually.`,'condition');commit(`${pokemon(id)?.name||'Pokémon'} Status Affliction updated.`);render();}
function pokemonCombatHydrationAvailability(id,data){const row=pokemonCombatHydrationRow(data),frequency=state.ui.weather==='rain'?'At-Will':'Scene',resource=pokemonCombatNonMoveSpec('ability','combat-hydration','Hydration','Swift Action',frequency),check=pokemonCombatNonMoveAvailability(id,resource),afflictions=pokemonCombatParticipant(id,{create:false})?.conditions?.statusAfflictions||[];if(!row)return {valid:false,reason:'This Pokémon does not have Hydration.'};const effect=String(row.definition?.effect||'').toLowerCase();if(!effect.includes('cured of one status affliction')||!effect.includes('rainy weather'))return {valid:false,row,reason:'Resolved Hydration differs from the audited February 2016 definition.'};return check.valid?{valid:true,row,resource,afflictions}:{...check,row,resource,afflictions};}
async function pokemonCombatUseHydration(id,status){const data=pokemonCombatReferenceState.pokemonId===id?pokemonCombatReferenceState.data:null,check=pokemonCombatHydrationAvailability(id,data);if(!check.valid)return toast(check.reason||'Hydration is unavailable.','error');if(!check.afflictions.includes(status))return toast('Select one currently marked Status Affliction to cure.','error');const spent=pokemonCombatSpendNonMoveResource(id,check.resource,{log:false});if(!spent.valid)return toast(spent.reason||'Hydration resource could not be spent.','error');pokemonCombatSetStatusAffliction(id,status,false);pokemonCombatLog(id,'Hydration',`${status} cured · Swift Action · ${state.ui.weather==='rain'?'Frequency ignored in Rainy Weather':'Scene'}.`,'ability');await commit(`${pokemon(id)?.name||'Pokémon'} used Hydration.`);render();return {valid:true,spent,status};}
function pokemonCombatIceBodyAvailability(id,data){const row=pokemonCombatIceBodyRow(data),p=pokemon(id),max=Number(p?.maxHp||p?.maxHP||p?.max_hp||0),hp=Number(p?.hp||0),weather=state.ui.weather,resource=pokemonCombatNonMoveSpec('ability','combat-ice-body','Ice Body','Swift Action','Daily x5'),check=pokemonCombatNonMoveAvailability(id,resource);if(!row)return {valid:false,reason:'This Pokémon does not have Ice Body.'};const effect=String(row.definition?.effect||'').toLowerCase(),bonus=String(row.definition?.bonus||'').toLowerCase();if(!effect.includes('tick of hit points')||!effect.includes('under 50% hit points')||!bonus.includes('immune to hit point loss from hail'))return {valid:false,row,reason:'Resolved Ice Body differs from the audited February 2016 definition.'};if(!(max>0)||!(hp*2<max||weather==='hail'))return {valid:false,row,resource,reason:'Ice Body can be used only below 50% HP or in Hailing Weather.'};return check.valid?{valid:true,row,resource,hp,max,tick:Math.max(1,Math.floor(max/10))}:{...check,row,resource,hp,max};}
async function pokemonCombatUseIceBody(id){const data=pokemonCombatReferenceState.pokemonId===id?pokemonCombatReferenceState.data:null,check=pokemonCombatIceBodyAvailability(id,data);if(!check.valid)return toast(check.reason||'Ice Body is unavailable.','error');const spent=pokemonCombatSpendNonMoveResource(id,check.resource,{log:false});if(!spent.valid)return toast(spent.reason||'Ice Body resource could not be spent.','error');const healing=await pokemonCombatApplyHpGain(id,check.tick,'Ice Body');pokemonCombatLog(id,'Ice Body',`${healing.applied} HP restored (one Tick: ${check.tick}) · Daily x5 · Swift Action.`,'ability');await commit(`${pokemon(id)?.name||'Pokémon'} used Ice Body.`);render();return {valid:true,spent,healing,tick:check.tick};}
function pokemonCombatHydrationIceBodyPanel(id,data){const hydration=pokemonCombatHydrationAvailability(id,data),ice=pokemonCombatIceBodyAvailability(id,data);if(!hydration.row&&!ice.row)return '';const known=['Paralyzed','Burned','Frozen','Poisoned','Badly Poisoned','Asleep'],marked=new Set(hydration.afflictions||[]),statuses=known.map(status=>`<label class="chip"><input type="checkbox" ${marked.has(status)?'checked':''} onchange="pokemonCombatSetStatusAffliction('${id}','${status}',this.checked)"> ${status}</label>`).join(' '),weather=String(state.ui.weather||'clear');return `<article class="ability-card"><h3>Combat Weather</h3><label>Current weather<select onchange="pokemonCombatSetWeather(this.value)"><option value="clear" ${weather==='clear'?'selected':''}>Clear / other</option><option value="rain" ${weather==='rain'?'selected':''}>Rainy</option><option value="hail" ${weather==='hail'?'selected':''}>Hail</option></select></label><small>Weather is a manually tracked session fact.</small></article>${hydration.row?`<article class="ability-card"><h3>Hydration</h3><p>February 2016: cure one Status Affliction · Scene – Swift Action; frequency is ignored during Rainy Weather.</p><div class="row-gap">${statuses}</div><button class="btn ${hydration.valid&&marked.size?'btn-gold':'btn-disabled'} full" ${hydration.valid&&marked.size?'':'disabled'} onclick="pokemonCombatUseHydration('${id}',${marked.size?JSON.stringify([...marked][0]):"''"})">Use Hydration · Swift Action · ${hydration.resource?.frequency||'Scene'}</button>${hydration.valid?'':`<small>${esc(hydration.reason||'Unavailable')}</small>`}</article>`:''}${ice.row?`<article class="ability-card"><h3>Ice Body</h3><p>February 2016: heal one Tick (${ice.tick||'1/10 max HP'}) · Daily x5 · Swift Action. May be used below 50% HP or during Hail; user is immune to HP loss from Hail.</p><button class="btn ${ice.valid?'btn-gold':'btn-disabled'} full" ${ice.valid?'':'disabled'} onclick="pokemonCombatUseIceBody('${id}')">Use Ice Body · Swift Action · Daily x5</button>${ice.valid?'':`<small>${esc(ice.reason||'Unavailable')}</small>`}</article>`:''}`;}'''

PANEL = r'''function pokemonCombatSourcePrecedencePanel(data){const rows=[['Quick Curl',pokemonCombatQuickCurlAbilityRow(data)],['Electrodash',pokemonCombatElectrodashDefinition(data?.abilities)],['Prime Fury',pokemonCombatResolveDefinition(data?.abilities,'Prime Fury')],['Hydration',pokemonCombatHydrationRow(data)],['Ice Body',pokemonCombatIceBodyRow(data)],['Vicious',pokemonCombatViciousAbilityRow(data)],['Hone Claws',pokemonCombatViciousHoneClawsRow(data)]].filter(([,row])=>row);if(!rows.length)return '';return `<details class="flow-note"><summary><strong>Resolved PTU sources</strong></summary><small>Core → 1.05 Editation → May 2015 → September 2015 → February 2016. Guards inspect the resolved winner.</small><div class="detail-dl">${rows.map(([name,row])=>{const source=pokemonCombatResolvedSource(row);return `<div><dt>${esc(name)}</dt><dd>${esc(source.label)}</dd></div>`;}).join('')}</div></details>`;}'''

CONDITION_PANEL = r'''function pokemonCombatConditionPanel(id,data){const row=pokemonCombatParticipant(id),rollout=row?.moveState?.rollout||{},knowsRoll=pokemonCombatKnowsRollMove(data),curl=pokemonCombatDefenseCurlModifier({curledUp:!!row?.conditions?.curledUp,moveName:'',knowsRollMove:knowsRoll});const parts=[];if(row?.conditions?.stuck)parts.push(`<div class="flow-note"><strong>Stuck</strong><small>Controlled status. Electrodash can remove it as a Shift Action.</small><button class="btn btn-ghost btn-small" onclick="pokemonCombatSetStuck('${id}',false)">Clear manually</button></div>`);else parts.push(`<button class="btn btn-ghost btn-small" onclick="pokemonCombatSetStuck('${id}',true)">Mark Stuck</button>`);if(Number(row?.conditions?.quickCurlDrRound)===Number(state.ui.round||1))parts.push(`<div class="flow-note"><strong>Quick Curl</strong><small>+10 Damage Reduction for this round.</small></div>`);if(Number(row?.conditions?.electrodashSprintRound)===Number(state.ui.round||1))parts.push(`<div class="flow-note"><strong>Electrodash Sprint</strong><small>Sprint was a Free Action; no Attacks of Opportunity while Sprinting this round.</small></div>`);if(Number(row?.conditions?.viciousCriticalRangeBonus||0)>0)parts.push(`<div class="flow-note"><strong>Vicious</strong><small>Critical Hit Range +${Number(row.conditions.viciousCriticalRangeBonus)} for all attacks · remains until this Pokémon leaves the current Combat session.</small></div>`);if(row?.conditions?.curledUp)parts.push(`<div class="flow-note"><strong>Curled Up</strong><small>Critical immunity · DR 10${curl.slowed?' · Slowed':' · Rollout/Ice Ball known: not Slowed'} · Rollout/Ice Ball gain +10 Damage and ignore the Curled Up Accuracy penalty.</small><button class="btn btn-ghost btn-small" onclick="pokemonCombatStopCurledUp('${id}')">Stop Curled Up · Swift Action</button></div>`);if(rollout.active)parts.push(`<div class="flow-note"><strong>Rollout locked</strong><small>${rollout.hits} consecutive hit${rollout.hits===1?'':'s'} · next base DB ${rollout.nextDb}. Other Moves are disabled until Rollout misses or no target can be hit.</small><button class="btn btn-ghost btn-small" onclick="pokemonCombatEndRollout('${id}')">No valid target · end chain</button></div>`);return parts.join('')||'<p class="muted">No tracked combat condition or chained Move state.</p>'; }'''

def patch(path):
    text=path.read_text(encoding='utf-8')
    if 'const PTU_COMBAT_SOURCE_PRECEDENCE=' in text:
        text=re.sub(r"const PTU_COMBAT_SOURCE_PRECEDENCE=\[[\s\S]*?(?=function pokemonCombatQuickCurlAbilityResourceSpec)",HELPERS+'\n',text,count=1)
    elif 'const PTU_COMBAT_SOURCE_PRECEDENCE=' not in text:
        anchor='function pokemonCombatQuickCurlAbilityResourceSpec()'
        if anchor not in text: raise SystemExit(f'precedence anchor missing: {path}')
        text=text.replace(anchor,HELPERS+'\n'+anchor,1)
    text=re.sub(r"function pokemonCombatQuickCurlAbilityResourceSpec\([\s\S]*?(?=function pokemonCombatRolloutAfterResult)",QUICK_CURL+'\n',text,count=1)
    if 'function pokemonCombatElectrodashClearStuckAvailability(' not in text and 'function pokemonCombatElectrodashResourceSpec(' in text:
        text=re.sub(r"function pokemonCombatElectrodashResourceSpec\([\s\S]*?(?=function pokemonCombatQuickCurlAbilityResourceSpec)",ELECTRODASH+'\n',text,count=1)
    elif 'function pokemonCombatElectrodashResourceSpec(' not in text:
        text=text.replace('function pokemonCombatQuickCurlAbilityResourceSpec()',ELECTRODASH+'\nfunction pokemonCombatQuickCurlAbilityResourceSpec()',1)
    if 'function pokemonCombatPrimeFuryAvailability(' not in text:
        text=text.replace('function pokemonCombatQuickCurlAbilityResourceSpec()',PRIME_FURY+'\nfunction pokemonCombatQuickCurlAbilityResourceSpec()',1)
    if 'function pokemonCombatHydrationIceBodyPanel(' not in text:
        text=text.replace('function pokemonCombatQuickCurlAbilityResourceSpec()',HYDRATION_ICE_BODY+'\nfunction pokemonCombatQuickCurlAbilityResourceSpec()',1)
    if "['Prime Fury',pokemonCombatResolveDefinition" not in text and 'function pokemonCombatSourcePrecedencePanel(' in text:
        text=re.sub(r"function pokemonCombatSourcePrecedencePanel\([\s\S]*?(?=function pokemonCombatElectrodashResourceSpec)",PANEL+'\n',text,count=1)
    elif 'function pokemonCombatSourcePrecedencePanel(' not in text:
        text=text.replace('function pokemonCombatElectrodashResourceSpec()',PANEL+'\nfunction pokemonCombatElectrodashResourceSpec()',1)
    panel="const electrodash=data?pokemonCombatElectrodashPanel(active.id,data):'';if(electrodash)body+=section('ELECTRODASH · SPRINT',electrodash);"
    anchor="const quickCurl=data?pokemonCombatQuickCurlPanel(active.id,data):'';"
    if panel not in text and anchor in text:text=text.replace(anchor,panel+anchor,1)
    fury_panel="const primeFury=data?pokemonCombatPrimeFuryPanel(active.id,data):'';if(primeFury)body+=section('PRIME FURY',primeFury);"
    fury_anchor="const electrodash=data?pokemonCombatElectrodashPanel(active.id,data):'';"
    if fury_panel not in text and fury_anchor in text:text=text.replace(fury_anchor,fury_panel+fury_anchor,1)
    health_panel="const hydrationIceBody=data?pokemonCombatHydrationIceBodyPanel(active.id,data):'';if(hydrationIceBody)body+=section('HYDRATION · ICE BODY · WEATHER',hydrationIceBody);"
    if health_panel not in text and fury_anchor in text:text=text.replace(fury_anchor,health_panel+fury_anchor,1)
    source_panel="const sources=data?pokemonCombatSourcePrecedencePanel(data):'';if(sources)body+=section('RULESET SOURCE RESOLUTION',sources);"
    source_anchor="body+=section('MANEUVERS'"
    if source_panel not in text and source_anchor in text:text=text.replace(source_anchor,source_panel+source_anchor,1)
    condition_anchor="const parts=[];"
    condition_extra="const parts=[];if(row?.conditions?.stuck)parts.push(`<div class=\"flow-note\"><strong>Stuck</strong><small>Controlled status. Electrodash can remove it as a Shift Action.</small><button class=\"btn btn-ghost btn-small\" onclick=\"pokemonCombatSetStuck('${id}',false)\">Clear manually</button></div>`);else parts.push(`<button class=\"btn btn-ghost btn-small\" onclick=\"pokemonCombatSetStuck('${id}',true)\">Mark Stuck</button>`);if(Number(row?.conditions?.quickCurlDrRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Quick Curl</strong><small>+10 Damage Reduction for this round.</small></div>`);if(Number(row?.conditions?.electrodashSprintRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Electrodash Sprint</strong><small>Sprint was a Free Action; no Attacks of Opportunity while Sprinting this round.</small></div>`);"
    if condition_extra not in text:
        if condition_anchor in text:text=text.replace(condition_anchor,condition_extra,1)
        else:text=re.sub(r"const parts=\[\];[\s\S]*?(?=if\(Number\(row\?\.conditions\?\.quickCurlDrRound)",condition_extra,text,count=1)
    duplicated="if(Number(row?.conditions?.quickCurlDrRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Quick Curl</strong><small>+10 Damage Reduction for this round.</small></div>`);if(Number(row?.conditions?.electrodashSprintRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Electrodash Sprint</strong><small>Sprint was a Free Action; no Attacks of Opportunity while Sprinting this round.</small></div>`);if(Number(row?.conditions?.quickCurlDrRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Quick Curl</strong><small>+10 Damage Reduction for this round.</small></div>`);if(Number(row?.conditions?.electrodashSprintRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Electrodash Sprint</strong><small>Sprint was a Free Action; no Attacks of Opportunity while Sprinting this round.</small></div>`);"
    single="if(Number(row?.conditions?.quickCurlDrRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Quick Curl</strong><small>+10 Damage Reduction for this round.</small></div>`);if(Number(row?.conditions?.electrodashSprintRound)===Number(state.ui.round||1))parts.push(`<div class=\"flow-note\"><strong>Electrodash Sprint</strong><small>Sprint was a Free Action; no Attacks of Opportunity while Sprinting this round.</small></div>`);"
    text=text.replace(duplicated,single)
    for fragment in [single.split(';')[0]+';',single.split(';')[1]+';']:
        first=text.find(fragment)
        if first>=0:text=text[:first+len(fragment)]+text[first+len(fragment):].replace(fragment,'')
    old="function pokemonCombatQuickCurlAbilityRow(data){return (data?.abilities||[]).find(row=>pokemonCombatSlug(row?.name||row?.definition?.name)==='quick-curl')||null;}"
    new="function pokemonCombatQuickCurlAbilityRow(data){return pokemonCombatResolveDefinition(data?.abilities,'Quick Curl');}"
    if old in text: text=text.replace(old,new,1)
    old="function pokemonCombatQuickCurlDefenseMoveRow(data){return (data?.moves||[]).find(row=>pokemonCombatSlug(row?.definition?.name||row?.record?.name)==='defense-curl')||null;}"
    new="function pokemonCombatQuickCurlDefenseMoveRow(data){return pokemonCombatResolveDefinition(data?.moves,'Defense Curl');}"
    if old in text: text=text.replace(old,new,1)
    old="function pokemonCombatViciousAbilityRow(data){return (data?.abilities||[]).find(row=>pokemonCombatSlug(row?.name||row?.definition?.name)==='vicious')||null;}"
    new="function pokemonCombatViciousAbilityRow(data){return pokemonCombatResolveDefinition(data?.abilities,'Vicious');}"
    if old in text: text=text.replace(old,new,1)
    old="function pokemonCombatViciousHoneClawsRow(data){return (data?.moves||[]).find(row=>pokemonCombatSlug(row?.definition?.name||row?.record?.name)==='hone-claws')||null;}"
    new="function pokemonCombatViciousHoneClawsRow(data){return pokemonCombatResolveDefinition(data?.moves,'Hone Claws');}"
    if old in text: text=text.replace(old,new,1)
    condition_start=text.find('function pokemonCombatConditionPanel(')
    condition_end=text.find('\nfunction ',condition_start+1) if condition_start>=0 else -1
    if condition_start<0 or condition_end<0:raise SystemExit(f'Combat condition panel anchor drifted: {path}')
    text=text[:condition_start]+CONDITION_PANEL+text[condition_end:]
    path.write_text(text,encoding='utf-8')

def main():
    for path in TARGETS: patch(path)
    print({'targets':len(TARGETS),'precedence':'core<1.05-editation<may-2015<september-2015<february-2016'})
if __name__=='__main__': main()
