#!/usr/bin/env python3
from __future__ import annotations

import base64
import hashlib
import json
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = ROOT.parent
PACK_ID = "campaign-homebrew-fakemon-1-leva"
VERSION = "2.0.1"
SOURCE_ID = "fakemon-1-leva"
PACK = ROOT / "bundled-packs" / f"{PACK_ID}-{VERSION}.ptucp"
OUT = REPO_ROOT / "PTU_Companion_Android_Tauri" / "www" / "fakemon-v2-data.js"

KIND_FILES = {
    "species": "content/species.ndjson",
    "moves": "content/moves.ndjson",
    "abilities": "content/abilities.ndjson",
}


def parse_ndjson(raw: bytes) -> list[dict]:
    return [json.loads(line) for line in raw.decode("utf-8").splitlines() if line.strip()]


def image_mime(path: str) -> str:
    ext = Path(path).suffix.lower()
    if ext == ".webp":
        return "image/webp"
    if ext == ".png":
        return "image/png"
    if ext in {".jpg", ".jpeg"}:
        return "image/jpeg"
    raise RuntimeError(f"Unsupported portrait format: {path}")


def main() -> None:
    if not PACK.exists():
        raise RuntimeError(f"Pack must be built before the Android overlay: {PACK}")

    archive_bytes = PACK.read_bytes()
    archive_sha = hashlib.sha256(archive_bytes).hexdigest()
    with zipfile.ZipFile(PACK) as archive:
        manifest = json.loads(archive.read("manifest.json"))
        if manifest.get("id") != PACK_ID or manifest.get("version") != VERSION:
            raise RuntimeError(f"Unexpected pack manifest: {manifest.get('id')} {manifest.get('version')}")

        definitions: dict[str, list[dict]] = {}
        counts: dict[str, int] = {}
        for kind, path in KIND_FILES.items():
            rows = parse_ndjson(archive.read(path))
            if kind == "species":
                for row in rows:
                    asset_path = row.get("portrait_asset_path")
                    if not asset_path:
                        continue
                    payload = archive.read(asset_path)
                    mime = image_mime(asset_path)
                    row["portrait_data_url"] = f"data:{mime};base64,{base64.b64encode(payload).decode('ascii')}"
            definitions[kind] = rows
            counts[kind] = len(rows)

        edges = json.loads(archive.read("content/datasets/ptu_evolution_edges.json"))
        families = json.loads(archive.read("content/datasets/ptu_evolution_families.json"))

    if counts != {"species": 13, "moves": 8, "abilities": 3}:
        raise RuntimeError(f"Unexpected Android overlay counts: {counts}")

    pack = {
        "manifest": manifest,
        "archiveSha256": archive_sha,
        "archiveFilename": PACK.name,
        "counts": counts,
        "definitions": definitions,
        "evolutionEdges": edges,
        "evolutionFamilies": families,
        "enabledRulesets": ["all-provided-material"],
        "warnings": [],
    }
    payload = json.dumps(pack, ensure_ascii=True, separators=(",", ":"))

    # This script executes before mobile-api.mjs. It replaces the stale embedded
    # v1.x pack in the large mobile-data bundle with the v2 definitions without
    # having to rewrite that 40+ MB generated file by hand.
    js = f"""// Generated by build_fakemon_1_leva_mobile_bundle.py. Do not edit by hand.\n(() => {{\n  const pack = {payload};\n  const data = window.__PTU_MOBILE_DATA__;\n  if (!data) throw new Error('PTU mobile data bundle must load before Fakemon v2 overlay.');\n  const packId = String(pack.manifest.id);\n  const sourceIds = new Set((pack.manifest.source_ids || []).map(String));\n  const deep = value => JSON.parse(JSON.stringify(value));\n\n  // Remove the superseded embedded v1.x metadata and records for this pack.\n  data.packs = (data.packs || []).filter(p => String(p?.id || '') !== packId);\n  for (const [versionId, record] of Object.entries(data.records || {{}})) {{\n    if (String(record?.contentPackId || '') === packId) delete data.records[versionId];\n  }}\n  for (const [key, versionIds] of Object.entries(data.versionGroups || {{}})) {{\n    const next = (versionIds || []).filter(versionId => data.records?.[versionId]);\n    if (next.length) data.versionGroups[key] = next; else delete data.versionGroups[key];\n  }}\n\n  const packMeta = {{\n    id: packId, name: String(pack.manifest.name || packId), version: String(pack.manifest.version || '0.0.0'),\n    priority: Number(pack.manifest.priority ?? 100) || 100, kind: String(pack.manifest.kind || 'custom'),\n    browse_only: !!pack.manifest.browse_only, archive_filename: pack.archiveFilename, archive_sha256: pack.archiveSha256,\n    manifest: deep(pack.manifest), androidImported: false, bundledRuntimeOverlay: true\n  }};\n  data.packs.push(packMeta);\n\n  const toRecord = (kind, row) => {{\n    const raw = deep(row || {{}});\n    const logical = String(raw.logical_id || raw.id || '').trim();\n    if (!logical) throw new Error(`Bundled ${{kind}} record is missing logical_id/id.`);\n    const versionId = String(raw.definition_version_id || `${{kind}}:${{logical}}@${{packId}}`);\n    raw.logical_id = logical; raw.definition_version_id = versionId; raw.content_pack_id = packId;\n    const tags = Array.isArray(raw.tags) ? raw.tags : [];\n    return {{\n      kind, id: logical, name: raw.name || raw.display_name || logical, versionId, contentPackId: packId,\n      packName: packMeta.name, packKind: packMeta.kind, sourceId: String(raw.source_id || pack.manifest.source_ids?.[0] || packId),\n      sourcePage: raw.source_page == null ? null : Number(raw.source_page), priority: Number(raw.source_priority ?? packMeta.priority) || packMeta.priority,\n      pinned: false, needsReview: !!raw.needs_review, type: raw.type || (Array.isArray(raw.types) ? raw.types.join(' / ') : null),\n      category: raw.class || raw.category || raw.record_kind || raw.capability_kind || null, parentClass: raw.parent_class || null, tags,\n      trainingFeature: raw.training_feature === true || tags.some(t => String(t).toLowerCase() === 'training'), profession: raw.profession || null,\n      frequency: raw.frequency_text || raw.frequency_action_text || raw.frequency?.raw || null, effect: raw.effect_text || null,\n      prerequisites: raw.prerequisites_text || null, price: raw.price ?? null, damageBase: raw.damage_base ?? null, ac: raw.ac ?? null,\n      range: raw.range_text || null, contestType: raw.contest_type || null, contestEffect: raw.contest_effect || null,\n      dexNumber: raw.dex_number ?? raw.national_dex_number ?? null, enabledForCreation: raw.enabled_for_character_creation ?? null,\n      completeness: raw.mechanical_completeness || null, types: Array.isArray(raw.types) ? raw.types : [], baseStats: raw.base_stats || null,\n      abilities: raw.ability_slots || [], capabilities: raw.capabilities || [], levelUpMoves: raw.level_up_moves || [], raw, rawText: raw.raw_text || null,\n      semanticAutomation: raw.semantic_automation || null, compiledEffects: raw.compiled_effects || [], prerequisiteSemantics: raw.prerequisite_semantics || null,\n      defenseProfile: raw.type_defense_profile || null, evolution: raw.evolution || null, evolutionText: raw.evolution_text || null, skills: raw.skills || null,\n      skillsText: raw.skills_text || null, capabilitiesText: raw.capabilities_text || null, tmMoves: raw.tm_moves || [], tutorMoves: raw.tutor_moves || [],\n      eggMoves: raw.egg_moves || [], androidImported: false, bundledRuntimeOverlay: true\n    }};\n  }};\n\n  const affected = [];\n  data.records ||= {{}}; data.versionGroups ||= {{}};\n  for (const [kind, rows] of Object.entries(pack.definitions || {{}})) {{\n    for (const row of (Array.isArray(rows) ? rows : [])) {{\n      const record = toRecord(kind, row);\n      data.records[record.versionId] = record;\n      const key = `${{kind}}:${{record.id}}`;\n      data.versionGroups[key] = [...(data.versionGroups[key] || []).filter(v => v !== record.versionId), record.versionId];\n      affected.push([kind, record.id, record.versionId]);\n    }}\n  }}\n\n  data.evolutionEdges = (data.evolutionEdges || []).filter(edge => !sourceIds.has(String(edge?.source_id || '')));\n  for (const edge of (pack.evolutionEdges || [])) data.evolutionEdges.push({{...deep(edge), raw: deep(edge.raw || edge)}});\n  if (Array.isArray(data.evolutionFamilies)) {{\n    data.evolutionFamilies = data.evolutionFamilies.filter(family => !sourceIds.has(String(family?.source_id || '')));\n    data.evolutionFamilies.push(...(pack.evolutionFamilies || []).map(deep));\n  }}\n\n  for (const ruleset of (data.rulesets || [])) {{\n    const existing = (ruleset.packs || []).find(p => String(p?.pack_id || '') === packId);\n    const shouldInclude = !!existing || String(ruleset.id) === 'all-provided-material';\n    ruleset.packs = (ruleset.packs || []).filter(p => String(p?.pack_id || '') !== packId);\n    if (!shouldInclude) continue;\n    const maxPosition = Math.max(-1, ...ruleset.packs.map(p => Number(p.position ?? -1)));\n    const enabled = existing ? !!existing.enabled : true;\n    ruleset.packs.push({{\n      pack_id: packId, enabled, priority: packMeta.priority, position: existing?.position ?? (maxPosition + 1),\n      name: packMeta.name, kind: packMeta.kind, browse_only: packMeta.browse_only, version: packMeta.version, androidImported: false, bundledRuntimeOverlay: true\n    }});\n    data.resolved ||= {{}}; data.resolved[ruleset.id] ||= {{}};\n    for (const [kind, logicalId, versionId] of affected) {{\n      data.resolved[ruleset.id][kind] ||= {{}};\n      if (enabled) data.resolved[ruleset.id][kind][logicalId] = versionId;\n    }}\n  }}\n\n  window.__PTU_FAKEMON_V2_BUNDLED_PACK__ = pack;\n}})();\n"""
    OUT.write_text(js, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes, pack sha256={archive_sha})")


if __name__ == "__main__":
    main()
