import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {importContentPack,inspectContentPack} from '../definitions/pack-importer.mjs';
import {DefinitionRepository} from '../definitions/repository.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const packPath=path.join(root,'test-fixtures/content-packs/campaign-homebrew-custom-weapons-2.1.0.ptucp');
const inspected=inspectContentPack(fs.readFileSync(packPath));
assert.equal(inspected.manifest.version,'2.1.0');
const itemRows=fs.readFileSync(path.join(root,'test-fixtures/content-packs/PTU_Weapons_v2.1_CONTENTS.md'),'utf8');
assert(itemRows.includes('Weapon Store'));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ptu-weapon-store-'));
const db=path.join(tmp,'defs.sqlite3');
fs.copyFileSync(path.join(root,'seed/definitions/ptu_seed_v1.0.sqlite3'),db);
let repo=new DefinitionRepository(db);
const before=repo.countResolved({rulesetId:'all-provided-material',kind:'items'});
repo.close();
assert.equal(before,508,'default seed must include Weapon + Gear packs (508 resolved items)');
await importContentPack({buffer:fs.readFileSync(packPath),dbPath:db,backupDir:path.join(tmp,'backups'),enableRulesetId:'all-provided-material',archiveFilename:path.basename(packPath)});
repo=new DefinitionRepository(db);
const after=repo.countResolved({rulesetId:'all-provided-material',kind:'items'});
assert.equal(after,before,'updating the already-bundled Weapon pack must be catalog-idempotent');
const sword=repo.getResolved({rulesetId:'all-provided-material',kind:'items',id:'fine-large-sword'});
assert(sword?.raw?.shop_categories?.includes('Weapon Store'));
assert.equal(sword?.raw?.shop_visible,true);
repo.close();
const app=fs.readFileSync(path.join(root,'static-preview/app.js'),'utf8');
assert(app.includes("invalidateItemCatalog(); await refreshDefinitionRows"),'pack import must invalidate Add Game Item cache');
assert(app.includes("setShopPreset('Weapon Store',0)"),'Weapon Store preset missing');
assert(app.includes("shops.includes('Weapon Store')"),'Weapon Store metadata filter missing');
assert(app.includes('ensureInventoryItemForPurchase'),'Weapon Store checkout must create backpack items from catalog definitions');
assert(app.includes("function supportsAutomatedItemUse(item){return ['potion','super-potion','oran-berry'].includes(item?.id);}"),'only items with implemented effects may expose an automated use action');
assert(app.includes('Effect not automated'),'unsupported consumables must show a persistent reason instead of a dead action button');
assert(app.includes('already at its current healing limit'),'healing items must not be consumed when they cannot restore HP');
const server=fs.readFileSync(path.join(root,'server.mjs'),'utf8');
assert(server.includes('shopCategories:Array.isArray(raw.shop_categories)'),'item catalog must expose shop metadata');
console.log(`PTU Companion Beta v2.1.0-beta.32 bundled Weapon Store verification: OK (${before} -> ${after} items after update)`);
