import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const app=fs.readFileSync(path.join(root,'static-preview/app.js'),'utf8');
const css=fs.readFileSync(path.join(root,'static-preview/styles.css'),'utf8');
const repo=fs.readFileSync(path.join(root,'definitions/repository.mjs'),'utf8');
const ok=(v,m)=>{if(!v)throw new Error(m)};
ok(app.includes('definitionArtworkHtml(d)'), 'Rules Library artwork helper missing');
ok(repo.includes('portraitDataUrl:raw.portrait_data_url'), 'Definition artwork summary fields missing');
ok(app.includes('<span>Adjusted Base</span><span>Existing alloc.</span>'), 'Adjusted Base progression column missing');
ok(app.includes('openPokemonProgressAbilityInfo'), 'Ability details modal action missing');
ok(app.includes('openPokemonProgressMoveInfo'), 'Move details modal action missing');
ok(app.includes('🐾 Open in Creatures'), 'Direct Creatures navigation missing');
ok(css.includes('.ability-choice{display:grid'), 'Ability alignment styles missing');
ok(app.includes('const nestedScroll=previous&&preserveScroll&&sameScreen?'), 'Nested horizontal/vertical scroll capture missing');
ok(app.includes('saved.path.reduce((parent,index)=>parent?.children[index]??null,current)'), 'Nested scroll restoration after render missing');
ok(css.includes('.creature-detail-grid .section-title .btn-ghost{color:#1765ad}'), 'Creature edit button contrast missing');
ok(css.includes('.creature-detail-grid .section-title .btn-ghost:focus-visible{outline:2px solid #fff;outline-offset:2px}'), 'Creature edit button focus indicator missing');
ok(css.includes('.creature-detail-grid .section-title .btn-ghost:disabled{color:#536b7e;opacity:1;background:#dbe5ed}'), 'Creature edit button disabled contrast missing');
console.log('PTU Companion Beta v2.1.0-beta.32 visual/navigation verification: OK');
