import { useState } from 'react'
import { creatures, moveDefinitions } from '../mockData'
import { Chip, MiniStat, Progress, Section, TypeBadge } from '../components/UI'

export default function Creature(){
 const c=creatures[2]; const [tab,setTab]=useState('Sheet'); const [move,setMove]=useState(moveDefinitions[1])
 return <div className="page"><div className="creature-header"><img src={c.image}/><div><p className="eyebrow">INDIVIDUAL CREATURE SHEET</p><h1>{c.name} ♀</h1><p>{c.species} · Lv. {c.level}</p><div>{c.types.map(t=><TypeBadge key={t} type={t}/>)}</div></div><div className="creature-vitals"><strong>HP {c.hp}/{c.maxHp}</strong><Progress value={c.hp} max={c.maxHp} tone="yellow"/><Chip tone="yellow">HEAVILY INJURED</Chip><span>Loyalty {'♥'.repeat(c.loyalty)}♡</span></div></div>
 <div className="tabbar">{['Sheet','Moves','Abilities','Species','Type','Pokédex'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
 {tab==='Sheet' || tab==='Moves' ? <div className="creature-detail-grid"><Section title="COMBAT STATS"><div className="stat-stack">{Object.entries(c.stats).map(([k,v])=><MiniStat key={k} label={k} value={v} kind={k}/>)}</div><h4>Combat Stages</h4><div className="stage-list"><span>Attack <b>-1</b></span><span>Defense <b>0</b></span><span>Sp. Attack <b className="positive">+2</b></span><span>Speed <b className="positive">+1</b></span></div></Section><Section title="MOVE LIST"><div className="move-table">{moveDefinitions.map(m=><button className={move.name===m.name?'active':''} onClick={()=>setMove(m)} key={m.name}><strong>{m.name}</strong><TypeBadge type={m.type as any}/><span>{m.category}</span><span>DB {m.db}</span><span>AC {m.ac}</span></button>)}</div><div className="damage-preview"><h3>{move.name} — Resolved Preview</h3><div className="formula">2d6 + 23</div><p>DB 4 + STAB 2 → DB 6 → 2d6+8 + Attack 15.</p><small>This prototype displays pre-calculated values only; dice are rolled physically.</small></div></Section><Section title="MOVE DETAILS"><div className="move-detail-panel"><h2>{move.name}</h2><div><TypeBadge type={move.type as any}/> <Chip tone="red">{move.category}</Chip></div><dl><div><dt>Frequency</dt><dd>{move.frequency}</dd></div><div><dt>AC</dt><dd>{move.ac}</dd></div><div><dt>DB</dt><dd>{move.db}</dd></div><div><dt>Range</dt><dd>{move.range}</dd></div></dl><p>{move.effect}</p><div className="tag-row">{move.tags.map(x=><Chip key={x}>{x}</Chip>)}</div></div></Section><Section title="STATUS / SCENE"><div className="modifier-list"><span>🩹 Heavily Injured</span><span>🌀 Curse Mark · 2 rounds</span><span>🌧 Weather · None</span><span>🏞 Terrain · None</span></div></Section></div> : <div className="placeholder-tab"><h2>{tab}</h2><p>This screen uses the same tabbed architecture as the visual mockup. The production agent can bind real PTU data here.</p></div>}
 </div>
}
