import { readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { openDatabase } from '../persistence/database.mjs';
import { CampaignRepository } from '../persistence/repository.mjs';

const root=fileURLToPath(new URL('..',import.meta.url));
const app=readFileSync(join(root,'static-preview','app.js'),'utf8');
const styles=readFileSync(join(root,'static-preview','styles.css'),'utf8');
const seed=JSON.parse(readFileSync(join(root,'seed','default-state.json'),'utf8'));
const temp=join(root,'data','verify-v17.sqlite3');
rmSync(temp,{force:true});rmSync(`${temp}-wal`,{force:true});rmSync(`${temp}-shm`,{force:true});
const db=openDatabase(temp); const repo=new CampaignRepository(db);
repo.saveState({...seed,version:2},{createRevision:false});
if(repo.listProfiles().length!==1) throw new Error('Initial profile persistence failed');
const second=structuredClone(seed); second.activeProfileId='verify-second'; second.trainer.id='verify-second'; second.trainer.name='Second Trainer'; second.trainer.title='Tester'; second.trainer.gmGrants=[]; second.trainer.history=[]; second.pokemon=[]; second.rosters=[{id:'verify-roster',name:'Personal Team',role:'COMBAT',maxMembers:6,active:true,color:'#0b7b4b'}]; second.inventory=(second.inventory||[]).map(i=>({...i,qty:0})); second.npcs=[]; second.selectedPokemonId=null; second.selectedRosterId='verify-roster'; second.selectedNpcId=null; second.ui={screen:'trainer',trainerTab:'profile',creatureTab:'sheet',toast:null,round:1,scene:1,day:1,gmOverride:false};
repo.saveState(second,{createRevision:false});
if(repo.listProfiles().length!==2) throw new Error('Multiple Trainer profiles failed');
repo.setActiveProfileId('alex'); if(repo.loadState().trainer.name!=='Alex Rowan') throw new Error('Profile switching failed');
if(app.includes('onclick="if(event.target===this)closeModal()"')) throw new Error('Backdrop still closes modal');
for(const token of ["trainerTabButton('moves','Moves')",'GM_RESOURCE_TARGETS','openTrainerSwitcher','createTrainerProfile','resetTrainerSheet','openTrainerMoveSourcePicker']) if(!app.includes(token)) throw new Error(`Missing v1.7 UI token: ${token}`);
if(!styles.includes('.trainer-move-grid')||!styles.includes('.profile-switch-list')) throw new Error('v1.7 styles missing');
console.log('PTU Companion v1.7 verification: OK');
console.log('modal backdrop dismissal: disabled');
console.log('structured GM Grant targets: present');
console.log('multi-Trainer profiles + switching: passed');
console.log('Trainer Moves tab + provenance picker: present');
console.log('Trainer sheet reset workflow: present');
db.close(); rmSync(temp,{force:true});rmSync(`${temp}-wal`,{force:true});rmSync(`${temp}-shm`,{force:true});
